#!/bin/bash
# Generic on-device end-to-end verification for a TOS 7 Docker application.
# Generated by `tosdocker`; app-specific values come from ../tosapp.json.
#
# MUST run as the TOS administrator (uid 0): the official installer writes under
# /Volume1/@apps/DockerEngine/ and drives dockerd.
#
# Usage:  bash test/install-and-verify.sh [path/to/<appid>.tar.gz] [--keep]
set -u

HERE="$(cd "$(dirname "$0")/.." && pwd)"
PKG="${1:-$HERE/out/pkg.tar.gz}"
KEEP=0
[ "${2:-}" = "--keep" ] && KEEP=1
[ "${1:-}" = "--keep" ] && { KEEP=1; PKG="$HERE/out/pkg.tar.gz"; }

SPEC="$HERE/tosapp.json"
[ -s "$SPEC" ] || { echo "ERROR: tosapp.json not found next to test/"; exit 1; }
j() { python3 -c "import json,sys;d=json.load(open('$SPEC'));print($1)"; }

APPID=$(j "d['app_id']")
PORT=$(j "d['host_port']")
MODE=$(j "d.get('mode','plain')")
USERSPEC=$(j "d.get('user','1000:1000')")
UIDSPEC="${USERSPEC%%:*}"
VOL0=$(j "d['volumes'][0]['host']")
DATA="/Volume1/DockerAppData/$APPID"
DOCKER="${TOSDOCKER_DOCKER:-/Volume1/@apps/DockerEngine/dockerd/bin/docker}"
TOOL="$HERE/TOSAppSelfTestingTool"
HTTP_PATH=$(j "d.get('http_path','/')")
# Some applications learn their own public address from the first HTTP request
# (a wrapper that captures the Host header). Probing those over 127.0.0.1 would
# pin the wrong address, so a spec may set `probe_host: auto` to probe the NAS
# LAN address instead - the address a real user (and the store reviewer) types.
PROBE_HOST_SPEC=$(j "d.get('probe_host','')")
PROBE_HOST=""
if [ "$PROBE_HOST_SPEC" = auto ]; then
  PROBE_HOST=$(ip -4 -o addr show scope global 2>/dev/null | awk '{print $4}' \
               | cut -d/ -f1 | grep -v '^172\.' | head -1)
fi
[ -n "$PROBE_HOST" ] || PROBE_HOST="$PROBE_HOST_SPEC"
[ -n "$PROBE_HOST" ] || PROBE_HOST=127.0.0.1
# Docker socket exception (spec: docker_socket: true). The socket is a bind mount
# source like any other, so the official installer may chown it: snapshot the
# host permissions before installing and put them back if they change.
SOCKET_EXC=no
[ "$(j "d.get('docker_socket',False)")" = "True" ] && SOCKET_EXC=yes
SOCK=/var/run/docker.sock
SOCK_BEFORE=""
[ "$SOCKET_EXC" = yes ] && SOCK_BEFORE=$(stat -c '%u:%g:%a' "$SOCK" 2>/dev/null)
APP_VOLS=$(j "'|'.join(v['host']+':'+v['container'] for v in d['volumes'] if v['host'].startswith('/Volume1/DockerAppData/'))")

PASS=0; FAIL=0
ok()        { echo "  [ OK ] $*"; PASS=$((PASS+1)); }
bad()       { echo "  [FAIL] $*"; FAIL=$((FAIL+1)); }
info_note() { echo "  [info] $*"; }

[ "$(id -u)" = "0" ] || { echo "ERROR: must run as uid 0 (TOS admin account)"; exit 1; }
[ -s "$PKG" ] || { echo "ERROR: package not found: $PKG"; exit 1; }
[ -x "$TOOL" ] || { echo "ERROR: TOSAppSelfTestingTool missing at $TOOL"; exit 1; }

echo "== 0/6  pre-clean (old containers / port) =="
for n in $("$DOCKER" ps -a --format '{{.Names}}' 2>/dev/null | grep -E "^${APPID}(_[0-9]+)?$"); do
  echo "   removing old container: $n"
  "$DOCKER" rm -f "$n" >/dev/null 2>&1 || true
done
if ss -tln 2>/dev/null | grep -q ":${PORT} "; then
  echo "   !! port ${PORT} is in use by something else:"
  ss -tlnp 2>/dev/null | grep ":${PORT} "
  exit 1
fi

echo
echo "== 1/6  official check + install (-i) =="
"$TOOL" -i "$PKG" || { echo "install failed"; exit 1; }

echo
echo "== 2/6  wait until the service answers =="
ready=no
for i in $(seq 1 45); do
  if curl -fsS -m 3 "http://127.0.0.1:${PORT}${HTTP_PATH}" >/dev/null 2>&1; then
    ready=yes; echo "   ready after ~$((i * 2))s"; break
  fi
  sleep 2
done
[ "$ready" = yes ] || echo "   timeout - continuing with diagnostics"

echo
echo "== 3/6  service / non-root / ports =="
"$DOCKER" ps -a --filter "name=^${APPID}$" --format '  {{.Names}} | {{.Image}} | {{.Status}} | {{.Ports}}'
hstat=starting
for _ in $(seq 1 20); do
  hstat=$("$DOCKER" inspect "$APPID" --format '{{.State.Health.Status}}' 2>/dev/null)
  [ "$hstat" = healthy ] && break
  sleep 3
done
[ "$hstat" = healthy ] && ok "healthcheck = healthy" || bad "healthcheck = ${hstat:-unknown}"
uid=$("$DOCKER" exec "$APPID" id -u 2>/dev/null)
[ "$uid" = "$UIDSPEC" ] && ok "runs as uid $UIDSPEC (non-root)" || bad "uid=$uid (expected $UIDSPEC)"
ss -tln 2>/dev/null | grep -q ":${PORT} " && ok "host port ${PORT} listening" || bad "host port ${PORT} not listening"
pub=$("$DOCKER" port "$APPID" 2>/dev/null)
npub=$(printf '%s\n' "$pub" | grep -c '^[0-9]')
if [ "$npub" = 2 ] && ! printf '%s\n' "$pub" | grep -v '^[0-9]*/tcp -> ' | grep -q '^[0-9]' \
   && printf '%s\n' "$pub" | grep -q ":${PORT}$"; then
  ok "only one container port published, on host ${PORT}"
else
  bad "unexpected port publishing: $(printf '%s' "$pub" | tr '\n' ' ')"
fi
if [ "$MODE" = wrapper ]; then
  cmd=$("$DOCKER" inspect "$APPID" --format '{{json .Config.Cmd}}' 2>/dev/null)
  case "$cmd" in
    *'exec '*) ok "the entrypoint script the container received is intact (no \$ interpolation damage)" ;;
    *) bad "container Cmd looks broken: $(printf '%s' "$cmd" | head -c 160)" ;;
  esac
fi
if [ "$SOCKET_EXC" = yes ]; then
  ga=$("$DOCKER" inspect "$APPID" --format '{{json .HostConfig.GroupAdd}}' 2>/dev/null)
  case "$ga" in
    *'"0"'*) ok "socket exception: supplementary group 0 applied ($ga)" ;;
    *) bad "group_add 0 is missing on the container: $ga" ;;
  esac
  if "$DOCKER" exec "$APPID" docker ps --format '{{.Names}}' >/dev/null 2>&1; then
    ok "the container really reaches the Docker daemon through the socket (docker ps)"
  else
    bad "the container cannot reach the Docker daemon (socket not mounted / wrong gid)"
  fi
  after=$(stat -c '%u:%g:%a' "$SOCK" 2>/dev/null)
  info_note "host socket perms: before install $SOCK_BEFORE, now $after"
  if [ "$after" = "$SOCK_BEFORE" ]; then
    ok "the installer left the host Docker socket untouched ($after)"
  else
    # Measured platform behaviour, not a defect of this package: the official
    # installer chowns *every* bind-mount source it parses, and the socket is
    # one. Keep the app working (group_add covers both cases), report it loudly
    # and put the host back the way it was.
    info_note "!! platform behaviour: the official installer chowned the host socket"
    info_note "   $SOCK: $SOCK_BEFORE -> $after (it chowns every mount source)"
    cu=$(printf '%s' "$SOCK_BEFORE" | cut -d: -f1)
    cg=$(printf '%s' "$SOCK_BEFORE" | cut -d: -f2)
    cm=$(printf '%s' "$SOCK_BEFORE" | cut -d: -f3)
    chown "$cu:$cg" "$SOCK" 2>/dev/null && chmod "$cm" "$SOCK" 2>/dev/null \
      && ok "host Docker socket restored to $SOCK_BEFORE (see docs/SOCKET-EXEMPTION.md)" \
      || bad "could not restore $SOCK to $SOCK_BEFORE"
  fi
fi

echo
echo "== 4/6  data directory =="
VOL0_CONT=$(j "d['volumes'][0]['container']")
owner=$(stat -c '%u' "$VOL0" 2>/dev/null)
[ "$owner" = "$UIDSPEC" ] && ok "volume $VOL0 owned by the app user (uid $UIDSPEC)" \
  || bad "volume $VOL0 owner uid=$owner (expected $UIDSPEC)"
# every application volume (the Docker socket, when the spec allows it, is not one)
IFS='|' read -r -a _av <<< "$APP_VOLS"
for pair in "${_av[@]}"; do
  [ -n "$pair" ] || continue
  vh="${pair%%:*}"; vc="${pair##*:}"
  [ "$vh" = "$VOL0" ] && continue
  o=$(stat -c '%u' "$vh" 2>/dev/null)
  [ "$o" = "$UIDSPEC" ] && ok "volume $vh owned by uid $UIDSPEC" \
    || bad "volume $vh owner uid=$o (expected $UIDSPEC)"
  if "$DOCKER" exec "$APPID" sh -c "touch $vc/.e2e-write && rm -f $vc/.e2e-write" >/dev/null 2>&1; then
    ok "the service can write into $vc"
  else
    bad "the service cannot write into $vc"
  fi
done
# the ownership of the app data root itself is platform-managed; what matters is
# that the service can really write into its mounted volume
owner_root=$(stat -c '%u' "$DATA" 2>/dev/null)
[ "$owner_root" = "$UIDSPEC" ] || info_note "app data root owner uid=$owner_root (platform-managed)"
if "$DOCKER" exec "$APPID" sh -c "touch $VOL0_CONT/.e2e-write && rm -f $VOL0_CONT/.e2e-write" \
     >/dev/null 2>&1; then
  ok "the service can write into $VOL0_CONT"
else
  bad "the service cannot write into $VOL0_CONT (a comment inside the compose volumes list, or the wrong uid)"
fi
[ -e "/Volume*/DockerAppData/${APPID}" ] \
  && bad "a literal /Volume*/DockerAppData/${APPID} exists (compose used the /Volume* wildcard)" \
  || ok "no literal /Volume* directory for this app"
RUNTIME_FILES=$(j "' '.join(f['path'] if isinstance(f, dict) else str(f) for f in d.get('runtime_files') or [])")
if [ -n "$RUNTIME_FILES" ]; then
  # Some applications create these files only once their own initialisation has
  # finished, which can lag behind the first HTTP response - poll before judging.
  for _ in $(seq 1 30); do
    pending=""
    for f in $RUNTIME_FILES; do [ -e "$DATA/$f" ] || pending="yes"; done
    [ -z "$pending" ] && break
    sleep 3
  done
  for f in $RUNTIME_FILES; do
    [ -e "$DATA/$f" ] && ok "runtime file present: $f" || bad "runtime file missing: $f"
  done
fi
[ -d "$VOL0" ] && ok "declared volume exists: $VOL0" || bad "declared volume missing: $VOL0"

echo
echo "== 5/6  functionality =="
code=$(curl -s -o /dev/null -w '%{http_code}' -m 8 "http://127.0.0.1:${PORT}${HTTP_PATH}" || true)
case "$code" in
  2*|3*) ok "HTTP ${HTTP_PATH} -> ${code}" ;;
  *) bad "HTTP ${HTTP_PATH} -> ${code:-no response}" ;;
esac
CONTENT_CONTAINER=$(j "(d.get('content_volume') or '')")
if [ -n "$CONTENT_CONTAINER" ]; then
  CONTENT_HOST=$(j "[v['host'] for v in d['volumes'] if v['container']==d.get('content_volume')][0]")
  marker="tosdocker-e2e-$$"
  echo "e2e $marker" > "$CONTENT_HOST/tosdocker-e2e.txt"
  sleep 1
  curl -fsS -m 8 "http://127.0.0.1:${PORT}/tosdocker-e2e.txt" 2>/dev/null | grep -q "$marker" \
    && ok "user content in ${CONTENT_CONTAINER} is served" || bad "user content not served"
  rm -f "$CONTENT_HOST/tosdocker-e2e.txt"
fi
if [ "$MODE" = wrapper ] && [ -n "$(j "d.get('config_file','')")" ]; then
  cf=$(j "d['config_file']")
  cp -f "$DATA/$cf" /tmp/tosdocker-e2e-cfg.bak 2>/dev/null || true
  printf 'this is not valid config\n' > "$DATA/$cf"
  "$DOCKER" restart "$APPID" >/dev/null 2>&1
  sleep 8
  h2=$("$DOCKER" inspect "$APPID" --format '{{.State.Health.Status}}' 2>/dev/null)
  [ "$h2" = healthy ] && ok "a broken user config does not take the app down (falls back)" \
                     || bad "broken config left the container $h2"
  cp -f /tmp/tosdocker-e2e-cfg.bak "$DATA/$cf" 2>/dev/null || true
  "$DOCKER" restart "$APPID" >/dev/null 2>&1
  sleep 6
fi
"$DOCKER" restart "$APPID" >/dev/null 2>&1
# Slow starters (they re-run migrations or rebuild caches) need more than a few
# seconds before the port answers again: poll instead of a fixed sleep.
code2=""
for _ in $(seq 1 40); do
  code2=$(curl -s -o /dev/null -w '%{http_code}' -m 8 "http://127.0.0.1:${PORT}${HTTP_PATH}" || true)
  case "$code2" in 2*|3*) break ;; esac
  sleep 3
done
case "$code2" in
  2*|3*) ok "still serving after a restart (${code2})" ;;
  *) bad "after restart: ${code2:-no response}" ;;
esac
marker2="keep-$$"
mkdir -p "$DATA/.e2e" && echo "$marker2" > "$DATA/.e2e/marker"
"$DOCKER" compose -p "$APPID" down >/dev/null 2>&1
[ -s "$DATA/.e2e/marker" ] && ok "uninstall (compose down) keeps the data directory" \
                           || bad "uninstall removed data"
"$TOOL" -i "$PKG" >/dev/null 2>&1 || true
for _ in $(seq 1 20); do
  curl -fsS -m 3 "http://127.0.0.1:${PORT}${HTTP_PATH}" >/dev/null 2>&1 && break
  sleep 2
done
[ -s "$DATA/.e2e/marker" ] && ok "reinstall keeps user data" || bad "reinstall lost user data"
rm -rf "$DATA/.e2e"

if [ "$SOCKET_EXC" = yes ]; then
  # The reinstall above chowns the socket again: leave the host exactly as we
  # found it (the app keeps working: group_add covers both ownerships).
  fin=$(stat -c '%u:%g:%a' "$SOCK" 2>/dev/null)
  if [ "$fin" = "$SOCK_BEFORE" ]; then
    ok "host Docker socket still as found ($fin)"
  else
    cu=$(printf '%s' "$SOCK_BEFORE" | cut -d: -f1)
    cg=$(printf '%s' "$SOCK_BEFORE" | cut -d: -f2)
    cm=$(printf '%s' "$SOCK_BEFORE" | cut -d: -f3)
    chown "$cu:$cg" "$SOCK" 2>/dev/null && chmod "$cm" "$SOCK" 2>/dev/null \
      && ok "host Docker socket put back to $SOCK_BEFORE (installer had left $fin)" \
      || bad "could not restore $SOCK to $SOCK_BEFORE"
  fi
fi

echo
echo "== 6/6  result =="
IP=$(ip -4 -o addr show scope global 2>/dev/null | awk '{print $4}' | cut -d/ -f1 | grep -v '^172\.' | head -1)
echo "   open      : http://${IP}:${PORT}${HTTP_PATH}"
echo "   data      : $DATA"
echo "   logs      : $DOCKER logs $APPID"
echo "   stop      : $DOCKER compose -p $APPID down   (data kept)"
if [ "$KEEP" = 1 ]; then
  echo "   --keep    : the app is left installed and running"
else
  "$DOCKER" rm -f "$APPID" >/dev/null 2>&1
  rm -rf "$DATA" "/Volume1/@apps/DockerEngine/application/$APPID"
  echo "   cleaned   : container + data + install dir removed (use --keep to keep them)"
fi
echo
echo "   passed ${PASS}, failed ${FAIL}"
[ "$FAIL" = 0 ]
