#!/bin/bash
# ===========================================================================
# Build the TOS 7 Docker application package (<appid>.tar.gz + .sha256).
#
# Generated by `tosdocker` (toolkit: /Volume1/projects/tosdocker). Everything app-specific
# lives in ./tosapp.json - this script is generic and reads it.
#
# Usage: scripts/build.sh [version] [platform]
#   version  default: tosapp.json "version"
#   platform default: tosapp.json "platform"  (x86_64 | aarch64)
#
# Pure Python + tar/gzip: no dpkg, no docker, no network needed.
# ===========================================================================
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT=$(pwd)
SRC="$ROOT/src"
STAGE="$ROOT/build/stage"
OUT="$ROOT/out"

APPID=$(python3 -c "import json;print(json.load(open('tosapp.json'))['app_id'])")

# --- version / platform: CLI argument wins, else tosapp.json ---------------
VERSION="${1:-$(python3 -c "import json;print(json.load(open('tosapp.json'))['version'])")}"
PLATFORM="${2:-$(python3 -c "import json;print(json.load(open('tosapp.json'))['platform'])")}"
case "$PLATFORM" in
  x86_64|aarch64) : ;;
  *) echo "FATAL: platform must be x86_64 or aarch64 (got '$PLATFORM')"; exit 1 ;;
esac
case "$VERSION" in
  *-0|*-0[0-9]*) echo "FATAL: packaging iteration must not be zero padded (got '$VERSION')"; exit 1 ;;
esac

# --- keep the spec in sync so a rebuild is reproducible --------------------
python3 - "$ROOT" "$VERSION" "$PLATFORM" <<'PY'
import json, pathlib, sys
root, ver, plat = pathlib.Path(sys.argv[1]), sys.argv[2], sys.argv[3]
p = root / "tosapp.json"
spec = json.loads(p.read_text(encoding="utf-8"))
if spec.get("version") != ver or spec.get("platform") != plat:
    spec["version"], spec["platform"] = ver, plat
    p.write_text(json.dumps(spec, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"   tosapp.json updated to version {ver} / platform {plat}")
PY

IMAGE=$(python3 -c "import json;print(json.load(open('tosapp.json'))['image'])")
echo ">> packaging ${APPID} version ${VERSION} platform ${PLATFORM} (image ${IMAGE})"

# ------------------------------------------------------------------ stage ----
rm -rf "$STAGE" "$OUT"
mkdir -p "$STAGE" "$OUT"
for f in config.ini "$APPID.lang" "$APPID.svg" docker-compose.yml; do
  cp "$SRC/$f" "$STAGE/$f"
done

python3 - "$SRC" "$STAGE" "$VERSION" "$PLATFORM" "$APPID" <<'PY'
import pathlib, sys
src, stage, ver, plat, appid = (pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2]),
                                sys.argv[3], sys.argv[4], sys.argv[5])

for name in ("config.ini", f"{appid}.lang"):
    p = stage / name
    data = p.read_text(encoding="utf-8").replace("@@VERSION@@", ver).replace("@@PLATFORM@@", plat)
    p.write_bytes(data.replace("\r\n", "\n").encode("utf-8"))

# The entrypoint wrapper (when the app uses one) is embedded into the compose
# block scalar. docker compose interpolates $VAR/${VAR} in compose files, so
# every '$' must be written '$$'; YAML then strips the block indentation again,
# so the script the container receives is byte-identical to src/entrypoint.sh.
comp = stage / "docker-compose.yml"
text = comp.read_text(encoding="utf-8")
if "        @@ENTRYPOINT_SH@@" in text:
    script = (src / "entrypoint.sh").read_text(encoding="utf-8")
    if "$$" in script:
        sys.exit("FATAL: src/entrypoint.sh must not contain '$$' (escaping would not be reversible)")
    escaped = script.replace("$", "$$")
    indented = "\n".join(("        " + l) if l.strip() else "" for l in escaped.splitlines())
    comp.write_text(text.replace("        @@ENTRYPOINT_SH@@", indented), encoding="utf-8")
    print(f"   staged entrypoint: {len(script.splitlines())} lines, {len(script)} bytes")
PY

# ---------------------------------------------------- build machine hygiene --
export COPYFILE_DISABLE=1
find "$STAGE" \( -name '._*' -o -name '.DS_Store' \) -delete
xattr -rc "$STAGE" 2>/dev/null || true
python3 - "$STAGE" <<'PY'
import sys, pathlib
for p in pathlib.Path(sys.argv[1]).rglob("*"):
    if p.is_file():
        b = p.read_bytes()
        if b.startswith(b"\xef\xbb\xbf"):
            b = b[3:]
        if b"\r\n" in b:
            b = b.replace(b"\r\n", b"\n")
        p.write_bytes(b)
PY

# ------------------------------------------------------- verify (hard gate) --
python3 "$ROOT/tools/verify.py" "$STAGE" "$VERSION" "$PLATFORM" "$ROOT"

# ------------------------------------------------------------------- pack ----
python3 - "$STAGE" "$OUT" "$APPID" <<'PY'
import tarfile, pathlib, gzip, io, sys
stage, out, appid = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2]), sys.argv[3]
tarpath = out / f"{appid}.tar.gz"
buf = io.BytesIO()
with tarfile.open(fileobj=buf, mode="w", format=tarfile.GNU_FORMAT) as tf:
    for p in sorted(stage.iterdir()):
        ti = tf.gettarinfo(str(p), arcname=p.name)
        ti.uid = ti.gid = 0
        ti.uname = ti.gname = "root"
        ti.mtime = 0
        ti.mode = 0o644
        with open(p, "rb") as fh:
            tf.addfile(ti, fh)
with open(tarpath, "wb") as fh:
    with gzip.GzipFile(fileobj=fh, mode="wb", compresslevel=9, mtime=0) as gz:
        gz.write(buf.getvalue())
print("packed", tarpath, f"{tarpath.stat().st_size} bytes")
PY

python3 - "$OUT" "$APPID" <<'PY'
import hashlib, pathlib, sys
out, appid = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
p = out / f"{appid}.tar.gz"
h = hashlib.sha256(p.read_bytes()).hexdigest()
(out / f"{appid}.tar.gz.sha256").write_text(f"{h}  {appid}.tar.gz\n")
print(f"{h}  {appid}.tar.gz")
PY

mkdir -p "$ROOT/test/compose-resolved"
cp "$STAGE/docker-compose.yml" "$ROOT/test/compose-resolved/docker-compose.yml"

echo ">> done:"
ls -la "$OUT"
