#!/usr/bin/env python3
"""Generic review-standards self-check for a TOS 7 Docker application package.

Generated by `tosdocker`. Reads ./tosapp.json (the app spec) and the staged
package directory; fails the build on any deviation.

    python3 tools/verify.py <stage-dir> <version> <platform> <project-root>
"""
import json
import pathlib
import re
import sys
import xml.etree.ElementTree as ET

CATEGORIES = {"Audio_Video_Entertainment", "Photography_Video", "Backup_Sync",
              "Development_Tools", "Utilities", "Web_Services", "Security",
              "Download", "Driver", "Artificial_Intelligence"}
REQUIRED_LANGS = set("zh-cn zh-hk en-us fr-fr de-de it-it es-es hu-hu ja-jp ko-kr "
                     "pl-pl ru-ru tr-tr pt-pt".split())
RESERVED_PORTS = (22, 80, 443, 445, 3306, 5050, 5432, 6379, 8181, 8443)

stage = pathlib.Path(sys.argv[1])
ver, plat = sys.argv[2], sys.argv[3]
root = pathlib.Path(sys.argv[4])
spec = json.loads((root / "tosapp.json").read_text(encoding="utf-8"))
appid = spec["app_id"]
mode = spec.get("mode", "plain")

errs = []


def chk(cond, msg):
    if not cond:
        errs.append(msg)


# ---- exactly the four required files at the archive root -------------------
names = sorted(p.name for p in stage.iterdir())
chk(names == sorted(["config.ini", f"{appid}.lang", f"{appid}.svg", "docker-compose.yml"]),
    f"archive must contain exactly 4 required files, got {names}")

# ---- config.ini -------------------------------------------------------------
raw_cfg = (stage / "config.ini").read_text(encoding="utf-8")
chk("@@" not in raw_cfg, "config.ini still contains an unreplaced @@PLACEHOLDER@@")
cfg = json.loads(raw_cfg)
chk(cfg["id"] == appid, "config.ini id must equal appid")
chk(cfg["version"] == ver, f"config.ini version must be {ver}")
chk(re.fullmatch(r"[0-9][0-9.]*-(?:[1-9][0-9]{0,2})", cfg["version"]) is not None,
    "version must be <digits.dots>-<iteration> (iteration >= 1, not zero padded)")
chk(cfg["application_type"] == "docker", "application_type must be docker")
chk("DockerEngine" in cfg["depend"], "depend must include DockerEngine")
chk("docker" in cfg["relation"] and "DockerEngine" in cfg["relation"],
    "relation must list docker + DockerEngine")
chk("type" not in cfg, "the iframe-only 'type' field must not appear (Docker apps use open_path)")
chk(cfg.get("open_path") is True, "open_path must be true")
chk(cfg["icon"] == f"/images/icons/{appid}.svg", "icon must be /images/icons/<appid>.svg")
chk(cfg["compose_project"] == appid, "compose_project must equal appid")
chk(cfg["platform"] == plat, f"config.ini platform must be {plat}")
chk(cfg.get("beta") is False, "beta must be false for a store submission")
chk(cfg.get("recommend") is False, "recommend must be false when submitting")
chk(cfg.get("publisher") == spec.get("publisher", "Moechz"),
    f"publisher must be {spec.get('publisher', 'Moechz')}")
chk(cfg.get("user") not in ("", "root", None), "a dedicated non-root user must be set")
chk(isinstance(cfg.get("category"), list) and 1 <= len(cfg["category"]) <= 3,
    "category must be a list of 1..3 categories")
for c in cfg.get("category", []):
    chk(c in CATEGORIES, f"category '{c}' is not an official category id")
for field in ("id", "icon", "publisher", "exec", "version", "low_version", "category",
              "depend", "platform", "application_type", "user", "all_user_display",
              "allow_open_in_mobile", "path", "open_path", "name"):
    chk(field in cfg, f"required config.ini field missing: {field}")
m = re.fullmatch(r"http://\$\{ip\}:(\d+)", cfg["path"])
chk(m is not None, "path must be http://${ip}:<port> (Docker app URL form)")
cfg_port = int(m.group(1)) if m else 0
chk(cfg_port == int(spec["host_port"]),
    f"config.ini path port {cfg_port} != spec host_port {spec['host_port']}")
chk(not re.search(r"\d+\.\d+\.\d+\.\d+", json.dumps(cfg, ensure_ascii=False)),
    "config.ini must not contain a hardcoded IP")
for key in ("help", "official", "Official"):
    v = cfg.get(key)
    if v:
        chk(v.startswith("https://github.com/"),
            f"{key} must be a github.com URL (the link checker performs an HTTP GET)")

# ---- lang -------------------------------------------------------------------
lang = (stage / f"{appid}.lang").read_text(encoding="utf-8")
chk("@@" not in lang, "lang still contains an unreplaced @@PLACEHOLDER@@")
secs = re.findall(r"^\[([a-z]{2}-[a-z]{2})\]$", lang, re.M)
chk(REQUIRED_LANGS.issubset(set(secs)),
    f"lang missing required languages: {sorted(REQUIRED_LANGS - set(secs))}")
chk(len(secs) == len(set(secs)), "lang has duplicate language sections")
for s in secs:
    body = lang.split(f"[{s}]", 1)[1].split("[", 1)[0]
    for key in ("name", "auth", "version", "descript", "release_note", "important"):
        mm = re.search(rf'{key}\s*=\s*"(.+)"', body)
        chk(mm is not None and mm.group(1).strip(), f"[{s}] {key} empty or missing")
    d = re.search(r'descript\s*=\s*"(.+)"', body)
    chk(d is None or len(d.group(1)) <= 512, f"[{s}] descript longer than 512 chars")
    i = re.search(r'important\s*=\s*"(.+)"', body)
    chk(i is None or len(i.group(1)) <= 512, f"[{s}] important longer than 512 chars")
    chk(f'version      = "{ver}"' in body, f"[{s}] version != {ver}")
chk(re.search(r"\bbeta\b", lang, re.I) is None, "lang must not contain the word 'beta' (V11)")

# ---- svg icon ---------------------------------------------------------------
svg_path = stage / f"{appid}.svg"
svg_bytes = svg_path.read_bytes()
chk(len(svg_bytes) <= 50 * 1024, f"icon too large: {len(svg_bytes)} bytes (limit 50 KB)")
svg_txt = svg_bytes.decode("utf-8")
try:
    svg_root = ET.fromstring(svg_txt)
    n_elems = sum(1 for _ in svg_root.iter())
    chk(svg_root.tag.endswith("svg"), "icon root element must be <svg>")
    chk("viewBox" in svg_root.attrib, "icon svg must declare viewBox")
    chk(n_elems <= 50, f"icon has {n_elems} elements (limit 50)")
except ET.ParseError as e:
    errs.append(f"icon is not valid XML: {e}")
    n_elems = -1
for banned in ("<filter", "<use", "sodipodi", "inkscape", "<metadata", "rdf:"):
    chk(banned not in svg_txt, f"icon must not contain {banned}")

# ---- docker-compose.yml -----------------------------------------------------
comp = (stage / "docker-compose.yml").read_text(encoding="utf-8")
comp_nc = "\n".join(l for l in comp.splitlines() if not l.lstrip().startswith("#"))
socket_ok = bool(spec.get("docker_socket"))
for banned in ("privileged", "network_mode", "cap_add", "pid:", "ipc:"):
    chk(banned not in comp_nc, f"compose must not use {banned}")
# The Docker socket is refused unless the spec carries the documented exception
# (docker_socket: true + docker_socket_reason + group_add). Apps that *are* a
# Docker control panel cannot work without it; everything else must not have it.
chk(socket_ok or "docker.sock" not in comp_nc,
    "compose must not use docker.sock (only allowed with docker_socket: true plus a "
    "written justification in the spec - it is a review exception, see PLAYBOOK.md)")
chk(socket_ok or "group_add" not in comp_nc,
    "group_add is a privilege escalation; it requires the documented docker_socket exception")
chk(re.search(r"ghcr\.io|quay\.io|lscr\.io|registry\.", comp_nc) is None,
    "images must come from Docker Hub (bare names)")
chk(":latest" not in comp_nc, "image must use a fixed tag, never :latest")
chk(f"image: {spec['image']}" in comp_nc, f"compose must pull exactly {spec['image']}")
upstream = spec.get("upstream_version") or ver.split("-")[0]
chk(re.search(rf"image:\s*{re.escape(spec['image'])}\s*$", comp_nc, re.M) is not None,
    "compose image must match tosapp.json exactly")
chk(re.search(rf"container_name:\s*{appid}\s*$", comp_nc, re.M) is not None,
    "main container_name must equal appid")
services = comp_nc.count("container_name:")
chk(services >= 1, "expected at least one service")
chk(comp_nc.count(f'user: "{spec.get("user", "1000:1000")}"') == services,
    f"every service must pin user {spec.get('user', '1000:1000')}")
chk(comp_nc.count("restart: unless-stopped") == services,
    "every service must use restart: unless-stopped")
chk(comp_nc.count("healthcheck:") == services, "every service must define a healthcheck")
chk(len(re.findall(r"^\s+TZ:\s*\S", comp_nc, re.M)) == services,
    "every service must set TZ explicitly")
chk(re.search(r"user:\s*[\"']?(0|root)", comp_nc) is None, "containers must not run as root")
vols = re.findall(r"^\s*-\s*(/[^:\s]+):(/[^:\s]+)\s*$", comp_nc, re.M)
app_vols = [(h, c) for h, c in vols]
sock_short = re.findall(
    r"^\s*-\s*(/var/run/docker\.sock):(/var/run/docker\.sock)\s*$", comp_nc, re.M)
sock_long = re.findall(
    r"^\s*-\s*\n\s*type:\s*bind\s*\n\s*source:\s*(/var/run/docker\.sock)\s*\n"
    r"\s*target:\s*(/var/run/docker\.sock)\s*$", comp_nc, re.M)
for host, cont in app_vols:
    if host == "/var/run/docker.sock":
        continue
    chk(host.startswith(f"/Volume1/DockerAppData/{appid}/"),
        f"volume source {host} must be below /Volume1/DockerAppData/{appid}/")
persistent = [(h, c) for h, c in app_vols if h != "/var/run/docker.sock"]
chk(len(persistent) >= 1, "at least one persistent volume mount is required")
if socket_ok:
    chk(comp_nc.count("docker.sock") == 2,
        "docker_socket: true must be the only reference to the socket in the compose "
        "file (the mount source and target)")
    # The long form is required on purpose: the installer chowns every mount
    # source it can read as "src:dst", and chowning /var/run/docker.sock to the
    # application uid would give the Docker socket to every uid-1000 container
    # on the NAS. Measured on hardware - see the exemption document.
    chk(not sock_short,
        "do not write the Docker socket as '- /var/run/docker.sock:/var/run/docker.sock': "
        "the official installer chowns mount sources and would chown the host socket "
        "to the application uid; use the YAML long form (see the generated spec/scaffold)")
    chk(sock_long == [("/var/run/docker.sock", "/var/run/docker.sock")],
        "docker_socket: true requires exactly one long-form bind mount of the socket "
        "(never a directory such as /var/run, never the Docker data root)")
    chk(re.search(r"^\s+group_add:\s*$", comp_nc, re.M) is not None
        and re.search(r'^\s+-\s*["\']?0["\']?\s*$', comp_nc, re.M) is not None,
        "docker_socket: true requires group_add with the socket's gid (0) - TOS sockets "
        "are root:root 0660 and a non-root container cannot open them otherwise")
    chk(str(spec.get("docker_socket_reason") or "").strip() != "",
        "docker_socket_reason is required: it is the justification sent to the reviewers")
chk("/Volume*" not in comp_nc, "never use the /Volume* wildcard (the platform does not expand it)")
seq_items = re.findall(r"^\s*-\s*(.*)$", comp_nc, re.M)
chk(not any(i.startswith("./") for i in seq_items),
    "relative './' volume mounts must not be used")
chk(comp_nc.rstrip().endswith("protocol: http"), "x-app-meta must be the last block")
chk("x-app-meta:" in comp_nc and f"port: {cfg_port}" in comp_nc,
    "x-app-meta web.port must match the config.ini path port")
ports = re.findall(r"^\s*-\s*[\"'](\d+):(\d+)[\"']\s*$", comp_nc, re.M)
chk(len(ports) == 1, f"compose must publish exactly one host port, got {ports}")
if len(ports) == 1:
    host, cont = int(ports[0][0]), int(ports[0][1])
    chk(host == cfg_port, f"published host port {host} != config.ini path port {cfg_port}")
    chk(host not in RESERVED_PORTS, f"host port {host} is reserved by TOS")
    chk(8000 <= host <= 19999, f"host port {host} outside the TOS-recommended range")
    if spec.get("container_port"):
        chk(cont == int(spec["container_port"]),
            f"container port {cont} != spec container_port {spec['container_port']}")
for pat, msg in ((r"(?i)(PASSWORD|SECRET|TOKEN|API_KEY):\s*\S",
                  "compose must not contain a literal secret"),
                 (r"(?i)user:\s*[\"']?root", "compose must not run as root")):
    chk(re.search(pat, comp_nc) is None, msg)
chk("curl -s -o /dev/null" in comp_nc or "wget -q" in comp_nc or "CMD [" in comp_nc,
    "the healthcheck must probe the service (curl/wget/CMD)")
bad_dollars = re.findall(r"(?<!\$)\$\{?[A-Za-z_]", comp_nc)
chk(not bad_dollars, f"unescaped '$' in compose (must be '$$'): {sorted(set(bad_dollars))}")
bad_seq = re.search(r"^([ \t]*)#[^\n]*\n\1-[ \t]", comp, re.M)
chk(bad_seq is None,
    "no comment may sit directly in front of a '- value' item (the official self-test "
    "tool parses the compose line by line and then skips its permission sync)")

# ---- the embedded entrypoint must match src/entrypoint.sh -------------------
if mode == "wrapper":
    chk('entrypoint: ["/bin/sh", "-c"]' in comp_nc,
        "the entrypoint wrapper must be installed")
    _m = re.search(r"^    command:\n      - \|\n(.*?)\n(?=^    [a-z_]+:)", comp, re.S | re.M)
    chk(_m is not None, "compose must embed the entrypoint under 'command:'")
    if _m:
        lines = [l[8:] if l.startswith(" " * 8) else l for l in _m.group(1).splitlines()]
        embedded = "\n".join(lines) + "\n"
        source = (root / "src" / "entrypoint.sh").read_text(encoding="utf-8")
        chk("$$" not in source, "src/entrypoint.sh must not contain '$$'")
        chk(embedded == source.replace("$", "$$"),
            "embedded entrypoint differs from src/entrypoint.sh")
        chk("set -u" in embedded, "entrypoint must keep 'set -u'")

if errs:
    print("VERIFY FAIL:")
    for e in errs:
        print("  -", e)
    sys.exit(1)
print(f"verify OK: files={names} langs={len(secs)} icon_elements={n_elems} "
      f"icon_bytes={len(svg_bytes)} host_port={cfg_port} volumes={len(vols)} mode={mode}")
